config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:index, :destroy]
  get "/sessions" => "sessions#destroy"
  resources :sessions, only: [:new, :create]
  
  resources :recipes do
    resources :ingredients
    resources :steps
  end
  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :steps
    has_many :ingredients
    belongs_to :user
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def authorize
    unless current_user
      redirect_to new_session_path
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
   def create
   @recipe = Recipe.find(params[:recipe_id])
   @ingredient = @recipe.ingredients.create(ingredient_params)
   redirect_to recipe_path(@recipe)
   end

 private
   def ingredient_params
     params.require(:ingredient).permit(:measurements, :amount, :item)
   end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   before_action :find_recipe, only: [:show, :destroy, :edit, :update]
   before_action :authorize, except: [:show, :index]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
     @recipe = Recipe.new(recipe_params)
     @recipe[:user_id] = current_user.id
     if @recipe.save
        redirect_to recipes_path
     else
        redirect_to new_recipes_path
     end
  end

  def show
     @recipe
  end

  def edit
     @recipe
  end

  def destroy
     @recipe.steps.destroy_all
     @recipe.ingredients.destroy_all
     @recipe.destroy
     redirect_to recipes_path
  end

  def update
     @recipe.update(recipe_params)
     redirect_to recipes_path
  end

  private

     def recipe_params
        params.require(:recipe).permit(:name, :cook_time, :prep_time, :url)
     end

     def find_recipe
        @recipe = Recipe.find(params[:id])
     end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  @current_session = User.find_by(email: params[:email]).try(:authenticate, params[:password])
    if @current_session
      session[:user_id] = @current_session.id
      redirect_to recipes_path
    else
      redirect_to new_session_path
    end
  end

  def destroy
    reset_session
    redirect_to new_session_path
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
    def create
      @recipe = Recipe.find(params[:recipe_id])
      @step = @recipe.steps.create(step_params)
      redirect_to recipe_path(@recipe)
    end

  private
    def step_params
      params.require(:step).permit(:description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to recipes_path
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
    <%= link_to "logout", sessions_path %>
    <%= link_to "profile", current_user %>
    <% else %>
      <%= link_to "login", new_session_path %>
      <%= link_to "Register", new_user_path %>
    <% end %>
    <%= link_to "home", recipes_path %>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :prep_time %><br>
      <%= f.text_field :prep_time %>
    </p>

    <p>
      <%= f.label :cook_time %><br>
      <%= f.text_field :cook_time %>
    </p>

    <p>
      <%= f.label :url %><br>
      <%= f.text_field :url %>
    </p>

    <p>
    <%= f.submit %>
    </p>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Your Recipe</h1>

<%= render "form", book: @recipe %>

<%= link_to "Back", recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipe List</h1>
<%= link_to "New Recipe", new_recipe_path %>

<br>
<br>
<% @recipes.each do |recipe| %>
    <p>
    <%= recipe.name %>
    <%= recipe.prep_time %>
    <%= recipe.cook_time %>
    <%= recipe.url %>
    <%= link_to 'Show', recipe_path(recipe) %>
    <%= link_to "Edit", edit_recipe_path(recipe) %>
    <%= link_to "Destroy", recipe, method: :delete %>
    </p>
<% end %>

app/views/recipes/new.html.erb
<h1>Create a new Recipe</h1>

<%= render "form" %>

<%= link_to "Back", recipes_path %>

app/views/recipes/show.html.erb
<p>
  <strong>Recipe:</strong>
  <%= @recipe.name %>
</p>
 
  <strong>prep_time:</strong>
  <%= @recipe.prep_time %>

  <strong>cook_time:</strong>
  <%= @recipe.cook_time %>

  <h2>Ingredients</h2>
<% @recipe.ingredients.each do |ingredient| %>
  <p>
    <strong>Measurement:</strong>
    <%= ingredient.amount %>
    <%= ingredient.measurements %>
  </p>
 
  <p>
    <strong>Ingredient:</strong>
    <%= ingredient.item %>
  </p>
<% end %>

<h2>Directions</h2>
<% @recipe.steps.each do |step| %>
  <p>
    <strong>Directions:</strong>
    <%= step.description %>
  </p>
<% end %>

<h2>Add a Ingredient:</h2>
<%= form_for([@recipe, @recipe.ingredients.build]) do |f| %>
  <p>
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </p>
  <p>
    <%= f.label :measurements %><br>
    <%= f.text_field :measurements %>
  </p>
  <p>
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<h2>Add a Direction:</h2>
<%= form_for([@recipe, @recipe.steps.build]) do |f| %>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit', edit_recipe_path(@recipe) %>
<%= link_to 'Back', recipes_path %>

app/views/users/new.html.erb
<h1>Create a New User</h1>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>User profile</h1>
<% @user.recipes.each do |recipe| %>
  <%= recipe.title %>
  <br>
<% end  %>